// privy/src/App.jsx
import { Orbis } from "@orbisclub/orbis-sdk";
import { PrivyProvider, useWallets, usePrivy } from "@privy-io/react-auth";

// Utility function explained in providerUtility.js
import { providerToBrowserProvider } from "./providerUtility";

import { useState, useEffect } from 'react'
import './App.css'

// https://docs.useorbis.com/sdk/introduction/getting-started
const orbis = new Orbis({});

function PrivyComponent() {
  // https://docs.privy.io/guide/frontend/authentication/status
  const privy = usePrivy()
  // https://docs.privy.io/guide/frontend/wallets/overview
  const { wallets } = useWallets()

  const [loading, setLoading] = useState(false)
  const [connection, setConnection] = useState(false)

  const connect = async (wallet) => {
    setLoading(true)
    // Check if the user is authentucated
    if (privy.authenticated) {
      // If no wallet provided, the call didn't come
      // from useEffect
      if (!wallet) return setLoading(false)

      // Fetch the raw Ethereum (request) provider
      const privyProvider = await wallet.getEthereumProvider()
      // Wrap the provider (more information in providerUtility.js)
      const orbisProvider = providerToBrowserProvider(privyProvider)

      const orbisConnection = await orbis.connect_v2({
        chain: "ethereum",
        provider: orbisProvider,
      });

      console.log("Orbis connection result", { orbisConnection });

      if (!orbisConnection.error) {
        setConnection(orbisConnection)
      }
    } else {
      // Initiate Privy login
      // Redirect-based oauth flow (unless e-mail OTP is used)
      privy.login()
    }

    setLoading(false)
  }

  const disconnect = async () => {
    setLoading(true)
    orbis.logout()
    if (privy.authenticated) {
      await privy.logout()
    }
    setLoading(false)
    setConnection(false)
  }

  useEffect(() => {
    // Look for Privy's embedded wallet and 
    // use it to connect to Orbis if it exists
    // https://docs.privy.io/guide/frontend/embedded/usage/address
    const wallet = wallets.find(w => w.walletClientType === "privy")
    if (wallet && !connection) {
      connect(wallet)
    }

    console.log("Current user wallets", { wallets })
  }, [wallets])

  // Alternatively, if you don't need a provider
  // instead of checking for Privy's session,
  // check Orbis local session directly
  // const connection = await orbis.isConnected()
  // More information - https://docs.useorbis.com/sdk/methods/connection/isConnected
  return (
    <main>
      {
        privy.authenticated ?
          <>
            {connection && <pre>{JSON.stringify(connection, null, 4)}</pre> || <h2>Waiting for wallet...</h2>}
            <button disabled={loading} onClick={disconnect}>
              Disconnect
            </button>
          </> :
          <button disabled={loading} onClick={connect}>Connect to Privy</button>
      }
    </main>
  )
}

function App() {
  // https://docs.privy.io/guide/quickstart
  return <PrivyProvider
    config={{
      embeddedWallets: {
        createOnLogin: 'all-users',
        noPromptOnSignature: true
      }
    }}
    appId="YOUR_PRIVY_APP_ID_HERE" // Obtained from the Privy console - https://console.privy.io/
  >
    <PrivyComponent />
  </PrivyProvider>
}

export default App

// web3auth/src/App.svelte
<script>
  import { Orbis } from "@orbisclub/orbis-sdk";
  import { Web3Auth } from "@web3auth/modal";

  // Utility function explained in providerUtility.js
  import { providerToBrowserProvider } from "./providerUtility";

  // https://docs.useorbis.com/sdk/introduction/getting-started
  const orbis = new Orbis({});

  // Web3Auth Modal docs - https://web3auth.io/docs/sdk/pnp/web/modal/usage
  const web3auth = new Web3Auth({
    uiConfig: {
      appName: "Orbis Social Demo", // Your dApp Name
      appLogo: "https://useorbis.com/img/orbis-logo.png", // Your dApp Logo URL
      theme: "dark", // "light" | "dark" | "auto"
      loginMethodsOrder: ["google", "apple", "twitter"],
      primaryButton: "socialLogin",
    },
    chainConfig: {
      chainNamespace: "eip155",
      chainId: "0x1",
    },
    clientId: "YOUR_CLIENT_ID_HERE", // Obtain from https://dashboard.web3auth.io/
    web3AuthNetwork: "cyan", // The network you set up your Web3Auth project on
  });

  // Store connection information to display
  let connection;

  // Utility variable to prevent multiple button clicks
  let loading = false;

  // Initialize the Web3Auth modal
  // Consolidate Web3Auth documentation for more information
  const initializeWeb3Auth = async () => {
    await web3auth.initModal({
      modalConfig: {},
    });

    await checkExistingSession();
  };

  const checkExistingSession = async () => {
    // If Web3Auth is connected we can connect to Orbis siltently
    if (!web3auth.connected) {
      return;
    }

    return connect();

    // Alternatively, you could use
    // const connection = await orbis.isConnected()
    // because session will be locally preserved for up to 3 months
    // It depends on your use case and whether you need the provider
    // More information - https://docs.useorbis.com/sdk/methods/connection/isConnected
  };

  const connect = async () => {
    loading = true;

    const web3AuthProvider = await web3auth.connect();
    const orbisProvider = providerToBrowserProvider(web3AuthProvider);

    const orbisConnection = await orbis.connect_v2({
      chain: "ethereum",
      provider: orbisProvider,
    });

    console.log("Orbis connection result", { orbisConnection });

    connection =
      orbisConnection.error || !orbisConnection.did ? false : orbisConnection;
    return (loading = false);
  };

  const disconnect = async () => {
    loading = true;
    orbis.logout();
    await web3auth.logout();
    connection = false;
    return (loading = false);
  };

  // Initialize Web3Auth and check for an existing connection
  let web3authPromise = initializeWeb3Auth();
</script>

<main>
  {#await web3authPromise}
    <h1>Initializing Web3Auth...</h1>
  {:then _}
    {#if connection}
      <pre>{JSON.stringify(connection, null, 4)}</pre>
      <button disabled={loading} on:click={disconnect}>Disconnect</button>
    {:else}
      <button disabled={loading} on:click={connect}
        >Connect with Web3Auth</button
      >
    {/if}
  {:catch}
    <h1>Error initializing Web3Auth</h1>
  {/await}
</main>

<style>
  main {
    margin: auto;
  }
</style>
