// magic/src/App.svelte
<script>
  import { Orbis } from "@orbisclub/orbis-sdk";
  import { Magic } from "magic-sdk";

  // Utility function explained in providerUtility.js
  import { providerToBrowserProvider } from "./providerUtility";

  // https://docs.useorbis.com/sdk/introduction/getting-started
  const orbis = new Orbis({});

  // Magic Plug'n'Play docs - https://magic.link/docs/universal/getting-started/quickstart
  const magic = new Magic(
    "YOUR_MAGIC_PUBLIC_ID_HERE", // Obtained from https://dashboard.magic.link/login
    {
      network: "mainnet",
    }
  );

  // Store connection information to display
  let connection;

  // Utility variable to prevent multiple button clicks
  let loading = false;

  const checkExistingSession = async () => {
    // Check if a local orbis session exists
    // More information - https://docs.useorbis.com/sdk/methods/connection/isConnected
    const orbisConnection = await orbis.isConnected();
    if (!orbisConnection) {
      if (await magic.user.isLoggedIn()) {
        connection = { onlyMagic: true };
      }

      return;
    }

    // Check if Magic is connected
    // You can skip this and subsequent checks if you don't
    // need a provider
    if (!(await magic.user.isLoggedIn())) {
      return;
    }

    // Grab the Magic Wallet signer
    const magicWallet = providerToBrowserProvider(
      await magic.wallet.getProvider()
    );
    const signer = await magicWallet.getSigner();

    // Grab Magic wallet's address
    const magicAddress = (await signer.getAddress()).toLowerCase();

    // Grab Orbis DID and extract the address
    const orbisAddress = orbisConnection.did.split(":").pop().toLowerCase();

    // Make sure that Magic and current Orbis user match
    if (magicAddress === orbisAddress) {
      return (connection = orbisConnection);
    }

    // Clear the session
    orbis.logout();
    return (connection = false);
  };

  const connect = async () => {
    loading = true;

    // Log into Magic
    await magic.wallet.connectWithUI();

    // Grab the magic provider
    const magicProvider = await magic.wallet.getProvider();
    // Wrap the provider (more information in providerUtility.js)
    const orbisProvider = providerToBrowserProvider(magicProvider);

    const orbisConnection = await orbis.connect_v2({
      chain: "ethereum",
      provider: orbisProvider,
    });

    console.log("Orbis connection result", { orbisConnection });

    if (orbisConnection.error) {
      if (connection.onlyMagic === true) {
        return (loading = false);
      }

      connection = false;
    } else {
      connection = orbisConnection;
    }

    return (loading = false);
  };

  const disconnect = async () => {
    loading = true;
    orbis.logout();
    await magic.user.logout();
    connection = false;
    return (loading = false);
  };

  // Check for an existing connection
  let checkSession = checkExistingSession();
</script>

<main>
  {#await checkSession}
    <h1>Initializing Magic...</h1>
  {:then _}
    {#if connection}
      {#if connection.onlyMagic === true}
        <div>
          You are already logged into Magic, but not connected to Orbis.
        </div>
        <button disabled={loading} on:click={connect}>Connect to Orbis</button>
        <button disabled={loading} on:click={disconnect}>Disconnect</button>
      {:else}
        <pre>{JSON.stringify(connection, null, 4)}</pre>
        <button disabled={loading} on:click={disconnect}>Disconnect</button>
      {/if}
    {:else}
      <button disabled={loading} on:click={connect}>Connect with Magic</button>
    {/if}
  {:catch}
    <h1>Error initializing Magic</h1>
  {/await}
</main>

<style>
  main {
    margin: auto;
  }
</style>

// privy/src/App.jsx
import { Orbis } from "@orbisclub/orbis-sdk";
import { PrivyProvider, useWallets, usePrivy } from "@privy-io/react-auth";

// Utility function explained in providerUtility.js
import { providerToBrowserProvider } from "./providerUtility";

import { useState, useEffect } from 'react'
import './App.css'

// https://docs.useorbis.com/sdk/introduction/getting-started
const orbis = new Orbis({});

function PrivyComponent() {
  // https://docs.privy.io/guide/frontend/authentication/status
  const privy = usePrivy()
  // https://docs.privy.io/guide/frontend/wallets/overview
  const { wallets } = useWallets()

  const [loading, setLoading] = useState(false)
  const [connection, setConnection] = useState(false)

  const connect = async (wallet) => {
    setLoading(true)
    // Check if the user is authentucated
    if (privy.authenticated) {
      // If no wallet provided, the call didn't come
      // from useEffect
      if (!wallet) return setLoading(false)

      // Fetch the raw Ethereum (request) provider
      const privyProvider = await wallet.getEthereumProvider()
      // Wrap the provider (more information in providerUtility.js)
      const orbisProvider = providerToBrowserProvider(privyProvider)

      const orbisConnection = await orbis.connect_v2({
        chain: "ethereum",
        provider: orbisProvider,
      });

      console.log("Orbis connection result", { orbisConnection });

      if (!orbisConnection.error) {
        setConnection(orbisConnection)
      }
    } else {
      // Initiate Privy login
      // Redirect-based oauth flow (unless e-mail OTP is used)
      privy.login()
    }

    setLoading(false)
  }

  const disconnect = async () => {
    setLoading(true)
    orbis.logout()
    if (privy.authenticated) {
      await privy.logout()
    }
    setLoading(false)
    setConnection(false)
  }

  useEffect(() => {
    // Look for Privy's embedded wallet and 
    // use it to connect to Orbis if it exists
    // https://docs.privy.io/guide/frontend/embedded/usage/address
    const wallet = wallets.find(w => w.walletClientType === "privy")
    if (wallet && !connection) {
      connect(wallet)
    }

    console.log("Current user wallets", { wallets })
  }, [wallets])

  // Alternatively, if you don't need a provider
  // instead of checking for Privy's session,
  // check Orbis local session directly
  // const connection = await orbis.isConnected()
  // More information - https://docs.useorbis.com/sdk/methods/connection/isConnected
  return (
    <main>
      {
        privy.authenticated ?
          <>
            {connection && <pre>{JSON.stringify(connection, null, 4)}</pre> || <h2>Waiting for wallet...</h2>}
            <button disabled={loading} onClick={disconnect}>
              Disconnect
            </button>
          </> :
          <button disabled={loading} onClick={connect}>Connect to Privy</button>
      }
    </main>
  )
}

function App() {
  // https://docs.privy.io/guide/quickstart
  return <PrivyProvider
    config={{
      embeddedWallets: {
        createOnLogin: 'all-users',
        noPromptOnSignature: true
      }
    }}
    appId="YOUR_PRIVY_APP_ID_HERE" // Obtained from the Privy console - https://console.privy.io/
  >
    <PrivyComponent />
  </PrivyProvider>
}

export default App
